# Generated by Django 5.2.5 on 2025-09-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0003_alter_offer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='offers/'),
        ),
    ]
