# Generated by Django 5.2.5 on 2025-09-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0004_offer_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='file',
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
    ]
